# ust REST Client Huachao Mao

###
POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
  "username": "rustfinity",
  "email": "rustfinity@example.com"
}

###

POST http://localhost:5000/docs HTTP/1.1
content-type: application/json

{
  "title": "First Post",
  "body": "This is the content of the first post.",
  "user_id": 1
}

###

POST http://localhost:5000/docs HTTP/1.1
content-type: application/json

{
  "title": "2nd doc",
  "body": "This is the content of the 2nd doc",
  "user_id": 1
}

###

POST http://localhost:5000/docs HTTP/1.1
content-type: application/json

{
  "title": "두번째 문서",
  "body": "호호호 안녕하신가?",
  "user_id": 1
}

###

GET http://localhost:5000/docs HTTP/1.1

###

GET http://localhost:5000/docs/1 HTTP/1.1

###

GET http://localhost:5000/users HTTP/1.1
